version: '3.6'

services:

  backend:
    build: backend
    hostname: backend-host
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    networks:
      - ares-network

  frontend:
    build: frontend
    hostname: frontend-host
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend-host:8000 
    ports:
      - "3001:3001"
    depends_on:
      - backend
    networks:
      - ares-network

networks:
  ares-network: {}
